### ISSUE TITLE
OSError: [Errno 5] Input/output error

### ISSUE THREAD

**Issue by rinzes** [RebelCodeBase/sopel-rss#8]
I was doing some testing and got this:

I loaded venv for python3
started sopel 

I issued .rss in the channel window which returned the following:

Traceback (most recent call last):
  File "/home/znc/.sopel-env/lib/python3.4/site-packages/sopel/bot.py", line 441, in call
    exit_code = func(sopel, trigger)
  File "/home/znc/.sopel-env/lib/python3.4/site-packages/sopel/module.py", line 343, in guarded
    return function(bot, trigger, _args, *_kwargs)
  File "/home/znc/.sopel/modules/rss3.py", line 178, in rss
    args = shlex.split(trigger.group(2))
  File "/usr/lib/python3.4/shlex.py", line 276, in split
    return list(lex)
  File "/usr/lib/python3.4/shlex.py", line 266, in **next**
    token = self.get_token()
  File "/usr/lib/python3.4/shlex.py", line 93, in get_token
    raw = self.read_token()
  File "/usr/lib/python3.4/shlex.py", line 121, in read_token
    nextchar = self.instream.read(1)
OSError: [Errno 5] Input/output error

It works ok with python2.7 with the following return:

synopsis: .rss add|del|fields|format|get|help|join|list|update

**Comment by RebelCodeBase** [comment]
This is python 3 code. It works with the Debian package in stretch and with my [ansible role](https://github.com/RebelCodeBase/ansible-role-sopel-runit-debian). Sorry, but debugging your system configuration setup is out of scope of this project.
